encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("add", views.add, name="add"),
    path("edit", views.edit, name="edit"),
    path("random", views.random, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from random import randint

from . import util

# search form class
class SearchQuery(forms.Form):
    query = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control form-control-sm', 'placeholder': 'Search Wiki'}))

# add entry form
class EditEntryForm(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'class': 'form-control mb-4', 'placeholder': 'Entry Title'}))
    content = forms.CharField(label="Entry Content", widget=forms.Textarea(attrs={'class': 'form-control my-2', 'placeholder': 'Entry Content'}))
    edit_type = forms.CharField(label="", widget=forms.HiddenInput())

# INDEX
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "search_form": SearchQuery
    })


# ENTRY gets the md entry if a title is found and if not, prompts user to create new entry
def entry(request, title):

    entry = util.get_entry(title)

    # if no entry found for title in URL, prompts user to create one
    if entry is None:
        no_entry_message = "No entry for " + title + " was found. Want to create one?"
        messages.add_message(request, messages.WARNING, no_entry_message)
        return render(request, "encyclopedia/entry.html", {
            "search_form": SearchQuery
        })

    # if title found, convert Markdown to HTML for entry page
    entry = util.converter(title)

    # go to that entry's page
    return render(request, "encyclopedia/entry.html", {
        "entry": entry,
        "title": title,
        "search_form": SearchQuery
    })


# SEARCH processes a search query submitted in the sidebar search form or redirects user back to index if reached by GET
def search(request):

    # if search request received from sidebar form
    if request.method == "POST":
        
        # get query from search form
        search_query = SearchQuery(request.POST)

        #server side form validation
        if search_query.is_valid():
            #cleaned_data gets all clean data from form, and in brackets can specify which variable inside that class you want
            query = search_query.cleaned_data["query"]

            entry = util.get_entry(query)

            # if an entry was found with that title, take user to that entry's page
            if entry is not None:
                return render(request, "encyclopedia/entry.html", {
                    "entry": entry,
                    "search_form": SearchQuery
                })

            # if no entry found, search for similar results and take to search results page
            else:

                # get all entry titles
                all_titles = util.list_entries()
                title_matches = []

                # iterate through all entry titles
                for title in all_titles:

                    entry = util.get_entry(title)

                    # look for query as substring of title
                    if query.lower() in title.lower():
                        title_matches.append(title)

                    # look for query as substring of entry
                    elif query.lower() in entry.lower():
                        title_matches.append(title)

                    # look for matching first letters of query and title
                    elif query[0].lower() == title[0].lower():
                        title_matches.append(title)

                # get number of matches which will determine formatting on search results page
                num_matches = len(title_matches)
                
                return render(request, "encyclopedia/search.html", {
                    "search_form": SearchQuery,
                    "query": query,
                    "title_matches": title_matches,
                    "num_matches": num_matches
                })

        # if server side validation fails
        else:
            # send user back to their form submission, and django will automatically generate a validation error message
            return render(request, "encyclopedia/index.html", {
                "entries": util.list_entries(),
                "search_form": search_query
            })

    # search page reached by GET, so redirect to index
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "search_form": SearchQuery
    })

def add(request):

    # if search request received from sidebar form
    if request.method == "POST":
        
        # get query from search form
        new_entry = EditEntryForm(request.POST)

        #server side form validation
        if new_entry.is_valid():
            
            title = new_entry.cleaned_data["title"] 
            edit_type = new_entry.cleaned_data["edit_type"] 

            entry = util.get_entry(title)

            # if there is no existing entry with the title
            if entry is None:

                title = title.capitalize()
                entry = new_entry.cleaned_data["content"]
                util.save_entry(title, entry)
                messages.add_message(request, messages.SUCCESS, 'New entry added successfully!')

            # if there is an existing entry...
            else:

                # and the user is attempting to create a new entry, give error message and take to existing entry page
                if edit_type == "new":
                    entry_exists_message = "There is already an entry for " + title + "!"
                    messages.add_message(request, messages.WARNING, entry_exists_message)

                # and if user is trying to edit that existing entry, save entry content from form
                elif edit_type == "edit":
                    entry = new_entry.cleaned_data["content"] 
                    util.save_entry(title, entry)
                    messages.add_message(request, messages.SUCCESS, 'Entry edited successfully!')

        entry = util.converter(title)

        return render(request, "encyclopedia/entry.html", {
            "entry": entry,
            "search_form": SearchQuery,
            "title": title
        })

    # ADD reached by GET so take to add entry form
    # initialize edit_type as new, as_p formats form as paragraphs
    add_entry_form = EditEntryForm(initial={'edit_type': 'new'}).as_p()

    return render(request, "encyclopedia/edit.html", {
        "search_form": SearchQuery,
        "entry_form": add_entry_form,
        "form_head": "Add New Entry"
    })

# EDIT entry view
def edit(request):

    # if reached from edit button
    if request.method == "POST":
        
        # get entry title from form
        edit_request = request.POST
        title = edit_request["title"]

        # get entry content as Markdown
        entry = util.get_entry(title)

        # pre-fill form with entry and title as values, as_p formats form as paragraphs
        entry_edit_form = EditEntryForm(initial={'title': title, 'content': entry, 'edit_type': 'edit'}).as_p()

        return render(request, "encyclopedia/edit.html", {
            "entry": entry,
            "search_form": SearchQuery,
            "entry_form": entry_edit_form,
            "form_head": "Edit Entry"
        })

    # reached by GET so go to index with message about needing to choose an entry to edit
    messages.add_message(request, messages.WARNING, 'Must choose an entry to edit.')
    return render(request, "encyclopedia/index.html", {
        "search_form": SearchQuery
    })

# display a RANDOM entry 
def random(request):

    # get all entry titles
    all_titles = util.list_entries()

    # generate a random integer between 0 and length of all_titles
    z = len(all_titles) - 1
    rando_num = randint(0, z)

    # index to rando_num in list of titles and convert to HTML
    rando_title = all_titles[rando_num]
    entry = util.converter(rando_title)

    return render(request, "encyclopedia/entry.html", {
            "entry": entry,
            "search_form": SearchQuery,
            "title": rando_title
        })

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <div class="row my-1">
        <div class="col">
            <h1><div id="form_head">{{ form_head }}</div></h1>
        </div>
    </div>
    <div class="row" my-1>
        <div class="col">
            <form action="{% url 'wiki:add' %}" method="POST">
                <div class="form-group row my-2">
                    <div class="col-8">
                        <h4>
                            {% csrf_token %}
                            {{ entry_form }}
                        </h4>
                    </div>
                    <div class="col-4"></div>
                </div>
                <div class="form-group row my-2">
                    <div class="col-8">
                        <button type="submit" class="btn btn-primary m-2">Save Entry</button>
                    </div>
                    <div class="col-4">{{ entry_form.edit_type.value}}</div>
                </div>
            </form>
        </div>
    </div>

<script>
    window.onload = function disableTitleField() {
        var edit_type = document.getElementById("form_head").innerHTML;
        if (edit_type == "Edit Entry") {
            document.getElementById("id_title").readOnly = true;
        }
        
    }
</script>

{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <div class="row my-1">
        <div class="col">
            <h1><div id="form_head">{{ form_head }}</div></h1>
        </div>
    </div>
    <div class="row" my-1>
        <div class="col">
            <form action="{% url 'wiki:add' %}" method="POST">
                <div class="form-group row my-2">
                    <div class="col-8">
                        <h4>
                            {% csrf_token %}
                            {{ entry_form }}
                        </h4>
                    </div>
                    <div class="col-4"></div>
                </div>
                <div class="form-group row my-2">
                    <div class="col-8">
                        <button type="submit" class="btn btn-primary m-2">Save Entry</button>
                    </div>
                    <div class="col-4">{{ entry_form.edit_type.value}}</div>
                </div>
            </form>
        </div>
    </div>

<script>
    window.onload = function disableTitleField() {
        var edit_type = document.getElementById("form_head").innerHTML;
        if (edit_type == "Edit Entry") {
            document.getElementById("id_title").readOnly = true;
        }
        
    }
</script>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<div id="entry" class="row">
    <div class="col-10">
        {{ entry|safe }}
    </div>  
    <div class="col-2"></div>
</div>

<div id="edit-btn" class="row">
    <div class="col-10">
        <form action="{% url 'wiki:edit' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" id="title" name="title" value="{{ title }}">
            <input class="btn btn-outline-dark btn-sm my-3" type="submit" value="Edit">
        </form>
    </div>
    <div class="col-2"></div>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>

                <form action="{% url 'wiki:search' %}" method="POST">
                    <div class="form-row my-3">
                        <div class="col-auto">
                            {% csrf_token %}
                            {{ search_form }}
                            <input type="submit" class="btn btn-outline-dark btn-sm my-3" value="Search">
                        </div>
                    </div>
                </form>
                    
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                <div class="row align-items-start">
                    <div class="col-10">

                        {% if messages %}
                        <div id="messages">
                            
                            {% for message in messages %}
                                <div class="alert alert-{% if message.tags %}{{ message.tags }}"{% endif %} role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}               
                        </div>
                        {% endif %}

                        {% block body %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search Results</h1>

    {% if num_matches == 0 %}
    
        <p>No results found. You can search again or <a href="{% url 'wiki:add' %}">create a new entry</a> for {{ query }}.</p>

    {% else %}
        <p>No entries with {{ query }} as title. Most comparable results: 

        <ul>

            {% for title in title_matches %}
                <li><a href="/wiki/{{ title }}">{{ title }}</a></li>
            {% endfor %}

        </ul>

    {% endif %}

{% endblock %}